config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome_page#welcome'
  devise_for :users, :controllers => { registrations: 'registrations' }

  # devise_for :users
  # get '/dashboard' => 'homepage#dashboard'

 
get '/profile' => 'welcome_page#specific_user'
# get '/profile/:id/edit' => 'devise/registrations#edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'opps#index'  
  # devise_for :users
  # resources :orgs
  #
  get '/queens' => 'opps#queens'
  get '/manhattan' => 'opps#manhattan'
  get '/bronx' => 'opps#bronx'
  get '/statenisland' => 'opps#statenisland'
  get '/brooklyn' => 'opps#brooklyn'
  get '/otherarea' => 'opps#otherarea'

  resources :opps do
    member do
      get 'bookmark'
      get 'unbookmark'
    end
  end

  resources :orgs do
    member do
      put "like", to: "orgs#like"
      put "unlike", to: "orgs#unlike"
    end
  end
end

app/models/org.rb
class Org < ApplicationRecord
  has_many :opps

  # acts_as_votable gem
  acts_as_votable
end

#milly

app/controllers/org_controller.rb
class OrgController < ApplicationController
    # before_action :authenticate_user! 

    # list method shows all orgs
    def index
      @orgs = Org.all
    end
    # show method - specific org profile page
    def show
      @org = Org.find(params[:id])
    end 
    
    def new
      @org = Org.new
    end
    
    def create
      @org = Org.create(org_params)
      if @org.save 
        redirect_to org_path
      end
    end
    
    def edit
      @org = Org.find(params[:id])
    end
    
    def update
      @org = Org.find(params[:id])
         
      if @org.update_attributes(org_params)
        redirect_to :action => 'show', :id => @org
      else
        render :action => 'edit'
      end
    end   
    
    def destroy
        @org = Org.find(params[:id])
        @org.destroy

        respond_to do |format|
        format.html {redirect_to org_path} #delete action in individual org page.
        format.js #delete via an ajax call if we decide to do implement it
    end
end

    private
    def org_params
        params.require(:org).permit(:name, :summary, :address, :website,
        :thumbnail, :phone)
        #the :created_at, :updated_at and :api_org_id are the other params
    end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  # before_action :authenticate_user!

  # list method shows all orgs
  def index
    @orgs = Org.all.page(params[:page])

  end

  # show method - specific org profile page
  def show
    @org = Org.find(params[:id])
    @current_person = current_user
    @org_opps = @org.opps
 
  end

  def new
    @org = Org.new
  end

  def create
    @org = Org.create(org_params)
    if @org.save
      redirect_to org_path
    end
  end

  def edit
    @org = Org.find(params[:id])
  end

  def update
    @org = Org.find(params[:id])

    if @org.update_attributes(org_params)
      redirect_to :action => 'show', :id => @org
    else
      render :action => 'edit'
    end
  end

  def destroy
    @org = Org.find(params[:id])
    @org.destroy

    respond_to do |format|
      format.html {redirect_to org_path} #delete action in individual org page.
      format.js #delete via an ajax call if we decide to do implement it
    end
  end

  def like
    @org = Org.find(params[:id])
    @org.liked_by current_user
    redirect_back(fallback_location: root_path)

  end

  def unlike
    @org = Org.find(params[:id])
    @org.unliked_by current_user
    redirect_back(fallback_location: root_path)

  end

  private

  def org_params
    params.require(:org).permit(:name, :summary, :address, :website,
                                :thumbnail, :phone)
    #the :created_at, :updated_at and :api_org_id are the other params
  end


end

app/helpers/org_helper.rb
module OrgHelper
end

app/views/orgs/_likes.html.erb
<% if current_user %>
  <% if !current_user.liked? @org %>

    <%= link_to like_org_path(@org), method: :put do %>
      <%= octicon "heart" %>
      <%= @org.get_likes.size %>
      Likes
    <% end %>
  <% else %>

    <%= link_to unlike_org_path(@org), method: :put do %>
      <%= octicon "heart" %>
      <%= @org.get_likes.size %>
      Likes
    <% end %>
  <% end %>
<% else %>
  <%= octicon "heart" %>
  <%= @org.get_likes.size %>
  Likes
<% end %>

app/views/orgs/edit.html.erb
<%#  Form to EDIT opportunity %>
<%#  Using @org here %>

app/views/orgs/index.html.erb
<%#  Listing of all Opportunities here %>
<%#  Using @orgs here %>

<div class="container">
<h3>Organizations</h3>
<% @orgs.each_with_index do |org, index| %>
<div class="row ">
    <div class="col-lg-12 card-header"><%= link_to org.name, {:action => 'show', :id => org.id} %> - <% @org = org %>
      <%= render "orgs/likes" %>
    </div>


  <div class="col-lg-3 m-auto">
    <% if org.thumbnail? %>
    <%= image_tag org.thumbnail, class: 'w-100' %>
    <% else %>
    <%= image_tag "/assets/default.jpg", class: 'w-100' %>
    <% end %>
  </div>

  <div class="col-lg-9 px-3">
    <div class="card-block px-3">
      <p class="card-text"><%= org.summary %></p>
    </div>
  </div>
</div>
<hr>
<% end %>
</div>
<div><%= paginate @orgs %></div>

app/views/orgs/new.html.erb
<%#  Form to CREATE opportunity %>
<%#  Using @org here %>

app/views/orgs/show.html.erb
<%#  Single opportunity page %>
<%#  Using @org here %>
<h3>Organization Profile</h3>
	<div class="card border-warning">
		<div class="card-body">
		  <div class="row">
		        <div class="card-header w-100"><%= @org.name%>  <%= render "orgs/likes" %></div>
            <div class="card-body">
              <h5 class="card-title"><%= @org.name%></h5>
              <p class="card-text"><b>Mission Statement :</b> <%= @org.summary %></p>
              <p class="card-text"><b>Address : </b><%= @org.address %></p>
              <p class="card-text"><b>Website :</b> <a href ='<%= @org.website %>'><%= @org.website %></a></p>
            </div>
          </div>
  </div>
</div>
<hr>


<h4>Current Opportunities</h4>
    <div class="row">
      <% @org_opps.each do |item| %>
                      <div class="col-md-6">
                        <div class="card border-warning bg-light mb-3">
                                <div class="card-header"><b><%= item.title.truncate(35) %></b><br>
                                <sub class="card-title"><%= item.start_date.strftime("%B %d, %Y") %> - <%= item.end_date.strftime("%B %d, %Y") %></sub>
                                </div>
                                <div class="card-body text-muted">
                                  <p class="card-text"><%= item.summary.truncate(100) %> </a> </p>
                                  
                                  <sub><%= link_to "More info", opp_path(item.id) %></a>
                        <% if current_user.liked? item %>
              <%= link_to unbookmark_opp_path(item.id), remote: true,
                          id: "bookmark_#{item.id}",
                          class: "text-danger" do %>
                <%= octicon "bookmark" %> Unbookmark
              <% end %>
            <% else %>
              <%= link_to bookmark_opp_path(item.id), remote: true,
                          id: "bookmark_#{item.id}",
                          class: "text-primary" do %>
                <%= octicon "bookmark" %>
                Bookmark
              <% end %>
            <% end %></sub>
                                    </div>
                                  
                                </div>
                      </div>
  <% end %>
</div>